### ISSUE TITLE
README lists incorrect command for deleting tracked URL

### ISSUE THREAD

**Issue by ChristopherJHart** [ConnorRigby/disclist#1]
README.md currently states the following:

> ### Remove 
> Remove a url from being scraped
> ```
> @Disclist remove https://slo.craigslist.org/search/hhh?query=hot%20dog%20stand&sort=rel
> ```

However, this command does not appear to be correct in the latest release: https://github.com/ConnorRigby/disclist/blob/master/lib/disclist/discord_consumer.ex#L26

README.md needs to be corrected with the proper command for removing tracked URLs.

**Comment by ConnorRigby** [comment]
Closed by #2
